import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { credentialStatus, statusClass } from "@/lib/credentials";
import { deleteStaff, updateExpiry, uploadCredential } from "@/app/actions";

export const dynamic = "force-dynamic";

export default async function StaffDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string }> }) {
  const { id } = await params; const query = await searchParams; const supabase = await createClient();
  const [{ data: person }, { data: types }, { data: docs }] = await Promise.all([supabase.from("staff_profiles").select("*").eq("id", id).single(), supabase.from("document_types").select("*").order("sort_order"), supabase.from("credential_documents").select("*").eq("staff_profile_id", id).order("expiry_date")]);
  if (!person) notFound();
  return <main className="shell"><Link className="back" href="/">← Staff dashboard</Link>{query.saved && <div className="success-banner">Saved. The status below is calculated from the persisted record.</div>}<header className="profile-head"><div className="avatar large">{person.full_name.split(" ").slice(0,2).map((word: string) => word[0]).join("")}</div><div><p className="eyebrow">{person.department}</p><h1>{person.full_name}</h1><p>{person.role} · IC {person.ic_number}</p></div><form action={deleteStaff} className="push"><input type="hidden" name="staff_profile_id" value={id}/><button className="button danger">Delete staff</button></form></header>
    <section className="panel"><div className="panel-head"><div><h2>Credential wallet</h2><p>Upload one current document into each slot.</p></div></div><div className="slots">{(types ?? []).map((type) => { const doc = (docs ?? []).find((item) => item.document_type_id === type.id); const status = credentialStatus(type.has_expiry, doc?.expiry_date, Boolean(doc)); return <article className="slot" key={type.id}><div className="slot-title"><div><h3>{type.name}</h3><p>{type.is_required ? "Required" : "Optional"} · {type.has_expiry ? "Expiry tracked" : "No expiry"}</p></div><span className={statusClass[status]}>{status}</span></div>{doc ? <div className="doc-detail"><div><strong>{doc.file_name}</strong><p>{doc.expiry_date ? `Expires ${new Intl.DateTimeFormat("en-MY", {dateStyle:"medium"}).format(new Date(`${doc.expiry_date}T00:00:00`))}` : "No expiry required"} · {doc.verification_status}</p></div>{type.has_expiry && <form action={updateExpiry} className="inline-form"><input type="hidden" name="staff_profile_id" value={id}/><input type="hidden" name="credential_id" value={doc.id}/><input type="date" name="expiry_date" defaultValue={doc.expiry_date ?? ""} required/><button className="button">Update expiry</button></form>}</div> : <form action={uploadCredential} className="upload-form" encType="multipart/form-data"><input type="hidden" name="staff_profile_id" value={id}/><input type="hidden" name="document_type_id" value={type.id}/><label>Document<input type="file" name="file" accept=".pdf,image/jpeg,image/png" required/></label><label>Issue date<input type="date" name="issue_date"/></label>{type.has_expiry && <label>Expiry date<input type="date" name="expiry_date" required/></label>}<button className="button primary">Upload</button></form>}</article>; })}</div></section>
  </main>;
}
